config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
  
  resources :categories do 
    resources :transactions
  end

  resources :users, only: %i[show]
  resources :home, only: %i[index]

  delete '/transactions', to: 'transactions#destroy_all'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Group.all.where(user_id: current_user.id)
  end

  def show
    @category = Group.find(params[:id])
  end

  def new
    Group.new
  end

  def edit
    @category = Group.find(params[:id])
  end

  def create
    @new_category = Group.new(group_params)

    if @new_category.save
      redirect_to categories_path, notice: 'Category successfully created'
    else
      render :new, alert: 'Oops, Something went wrong'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category successfully removed' }
    end
  end

  def update
    @category = Group.find(params[:id])

    respond_to do |format|
      if @category.update(group_params)
        format.html { redirect_to categories_path, notice: 'Changes was successfully saved.' }
      else
        format.html { render :edt, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_card.html.erb
<div class="category-cards">
  <div class="outer-icon-container">
    <%case category.icon %>
      <%when "entertainment"%>
        <div class="icon-container entertainment">
          <%=image_tag "entertainment.svg" %>
        </div>
      <%when "grosseries"%>
        <div class="icon-container grosseries">
          <%=image_tag "grosseries.svg" %>
        </div>
      <%when "utilities"%>
        <div class="icon-container utilities">
          <%=image_tag "utilities.svg" %>
        </div>
      <%when "housing"%>
        <div class="icon-container housing">
          <%=image_tag "housing.svg" %>
        </div>
      <%when "clothing"%>
        <div class="icon-container clothing">
          <%=image_tag "clothing.svg" %>
        </div>
      <%when "healthcare"%>
        <div class="icon-container healthcare">
          <%=image_tag "healthcare.svg" %>
        </div>
      <%when "transportation"%>
        <div class="icon-container transportation">
          <%=image_tag "transportation.svg" %>
        </div>
      <%when "miscellaneous"%>
        <div class="icon-container miscellaneous">
          <%=image_tag "miscellaneous.svg" %>
        </div>
    <% end %>
  </div>
  <div class="card-content">
    <div class="card-content-header">
      <h2 class="subheadings"><%= category.name %></h2>
      <h2 class="subheadings category-amount">$ <%= category.calculate_total %>.00</h2>
    </div>
    <div class="card-content-footer">
      <small><%= category.created_at.strftime("%d %B, %Y") %></small>
    </div>
  </div>
  <div class="category-actions">
    <%= link_to raw(image_tag "arrow-forward.svg"), category_path({id: category.id}), class: "arrows-links"%>
  </div>
</div>

app/views/categories/_category.html.erb
<div class="category-cards">
  <div class="outer-icon-container">
    <%case category.icon %>
      <%when "entertainment"%>
        <div class="icon-container entertainment">
          <%=image_tag "entertainment.svg" %>
        </div>
      <%when "grosseries"%>
        <div class="icon-container grosseries">
          <%=image_tag "grosseries.svg" %>
        </div>
      <%when "utilities"%>
        <div class="icon-container utilities">
          <%=image_tag "utilities.svg" %>
        </div>
      <%when "housing"%>
        <div class="icon-container housing">
          <%=image_tag "housing.svg" %>
        </div>
      <%when "clothing"%>
        <div class="icon-container clothing">
          <%=image_tag "clothing.svg" %>
        </div>
      <%when "healthcare"%>
        <div class="icon-container healthcare">
          <%=image_tag "healthcare.svg" %>
        </div>
      <%when "transportation"%>
        <div class="icon-container transportation">
          <%=image_tag "transportation.svg" %>
        </div>
      <%when "miscellaneous"%>
        <div class="icon-container miscellaneous">
          <%=image_tag "miscellaneous.svg" %>
        </div>
    <% end %>
  </div>
  <div class="card-content">
    <div class="card-content-header">
      <h2 class="subheadings"><%= category.name %></h2>
      <h2 class="subheadings category-amount">$ <%= category.calculate_total %>.00</h2>
    </div>
    <div class="card-content-footer">
      <small><%= category.created_at.strftime("%d %B, %Y") %></small>
    </div>
  </div>
  <div class="category-actions">
    <%= link_to raw(image_tag "arrow-forward.svg"), category_path({id: category.id}), class: "arrows-links"%>
  </div>
</div>

app/views/categories/_transaction.html.erb
<div class="category-cards transaction-cards">
  <div class="card-content transaction-content">
    <div class="card-content-header">
      <h2 class="subheadings"><%= transaction.name %></h2>
      <h2 class="subheadings category-amount">$ <%= transaction.amount %>.00</h2>
    </div>
    <div class="card-content-footer">
      <small><%= transaction.created_at.strftime("%d %B, %Y") %></small>
    </div>
  </div>
  <div class="category-actions">
    <%= link_to raw(image_tag "arrow-forward.svg"), category_transaction_path({id: transaction.id, category_id: transaction.group_id}), class: "arrows-links"%>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), category_path(@category.id) %>
    <h2 class="main-headings">Update category</h2>
  </div>
  <div class="forms-container">
    <%=form_with(model: @group, url: category_path, method: :put, local: true) do |f| %>
      <div class="field">
        <%= f.text_field :name, value: @category.name %>
      </div>

      <div class="field">
        <%= f.collection_select :icon, Group::ICONS, :to_s, :humanize %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="form-actions">
        <%= f.submit "Save changes", class: "creator-btns" %>
    <% end %>
        <%= button_to "Delete this category",
            category_path(id: params[:id]),
            method: :delete,
            style: "
              text-align: center;
              border: none;
              font-size: var(--heading-size);
              font-weight: var(--heding-font-weight);
              border-radius: 5px;
              background: #ffffff;
              " %>
      </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="main-categories-page">
  <div class="header">
    <%= link_to raw(image_tag "menu-icon.svg"), user_path({id: current_user.id}) %>
    <h1 class="main-headings">Categories</h1>  
  </div>
  
  <div class="main-content">
    <div class="main-dashbord">
      <h2 class="subheadings">Total spending for current period:<h2>
      <div class="innder-dashboard">
        <h3 class="total-ammount"> $
        <% if current_user.total_expense.positive? %>
        - <%= current_user.total_expense %>.00
        <% else %>
          <%= current_user.total_expense %>.00
        <% end %>
        </h3>
      </div>
    </div>

    <div class="categories-container">
      <% @categories.includes(:entities).each do |category| %>
        <%= render 'card', category: category %>
      <% end %> 
    </div>
  </div>
  <div class="categories-actions-outer">
    <div class="categories-actions-inner">
      <%= link_to raw(image_tag 'add-icon.svg'), new_category_path %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), categories_path %>
    <h2 class="main-headings">Add category</h2>
  </div>
  <div class="forms-container">
    <%=form_with(model: @group, url: categories_path, method: :post, local: true) do |f| %>
      <div class="field">
        <%= f.text_field :name, placeholder: "Category name"%>
      </div>

      <div class="field">
        <%= f.label "Icon type" %>
        <%= f.collection_select :icon, Group::ICONS, :to_s, :humanize %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="form-actions">
        <%= f.submit "Add Category", class: "creator-btns" %>
        <%= link_to "Cancel", categories_path, class: 'delete-btns'%>
      </div>
    <% end %>
  </div>
  </div>

app/views/categories/show.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), categories_path %>
    <h1 class="main-headings"><%= @category.name %></h1>
    <%= link_to raw(image_tag "settings-icon.svg"), edit_category_path({id: @category.id}) %>
  </div>
  
  <div class="main-content">
    <div class="main-dashbord">
      <h2 class="subheadings">Total spendings for <%= @category.name %><h2>
      <div class="innder-dashboard">
        <h3 class="total-ammount"> $
        <% if @category.calculate_total.positive? %>
        - <%= @category.calculate_total %>.00
        <% else %>
          <%= @category.calculate_total %>.00
        <% end %>
        </h3>
      </div>
    </div>

    <div class="categories-container">
      <% @category.entities.order(created_at: :desc).each do |transaction| %>
        <%= render 'transaction', transaction: transaction %>
      <% end %> 
    </div>
  </div>
  <div class="categories-actions-outer">
    <div class="categories-actions-inner">
      <%= link_to raw(image_tag 'add-icon.svg'), new_category_transaction_path({category_id: @category.id}) %>
    </div>
  </div>
</div>