config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
  
  resources :categories do 
    resources :transactions
  end

  resources :users, only: %i[show]
  resources :home, only: %i[index]

  delete '/transactions', to: 'transactions#destroy_all'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Entity.all.where(user_id: current_user.id)
  end

  def show
    @transaction = Entity.find(params[:id])
  end

  def new
    Entity.new
  end

  def edit
    @transaction = Entity.find(params[:id])
  end

  def create
    @new_entity = Entity.new(entity_params)

    if @new_entity.save
      redirect_to category_path(id: params[:category_id]), notice: 'Transaction successfully added'
    else
      render :new, alert: 'Oops, Something went wrong'
    end
  end

  def destroy
    Entity.find(params[:id]).delete
    respond_to do |format|
      format.html { redirect_to category_path(id: params[:category_id], notice: 'Transaction successfully removed') }
    end
  end

  def destroy_all
    Entity.all.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'All records  successfully removed' }
    end
  end

  def update
    @transaction = Entity.find(params[:id])

    respond_to do |format|
      if @transaction.update(entity_params)
        format.html do
          redirect_to category_transaction_path({ id: @transaction.id, category_id: @transaction.group_id }),
                      notice: 'Changes successfully saved'
        end
      else
        format.html { render :edt, status: :unprocessable_entity }
      end
    end
  end

  private

  def entity_params
    params.permit(:name, :amount, :user_id, :group_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), category_transaction_path(id: @transaction.id, category_id: @transaction.group_id) %>
    <h2 class="main-headings">Update transaction</h2>
  </div>
  <div class="forms-container">
    <h2></h1>
    <%=form_with(model: @entity, url: category_transaction_path, method: :put, local: true) do |f| %>
      <div class="field">
        <%= f.text_field :name, value: @transaction.name %>
      </div>

      <div class="field">
        <%= f.number_field :amount, value: @transaction.amount %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %> 
      <%= f.hidden_field :group_id, value: params[:category_id] %> 

      <div class="form-actions">
        <%= f.submit "Save changes", class: "creator-btns" %>
    <% end %>
      <%= button_to "Delete this category",
          category_transaction_path(id: params[:id]),
          method: :delete,
          style: "
          text-align: center;
          border: none;
          font-size: var(--heading-size);
          font-weight: var(--heding-font-weight);
          border-radius: 5px;
          background: #ffffff;
          " %>
      </div>
  </div>
  </div>

app/views/transactions/index.html.erb
<h2>All transactions are gonnna be here</h2>

app/views/transactions/new.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), category_path(params[:category_id]) %>
    <h2 class="main-headings">Add transaction</h2>
  </div>
  <div class="forms-container">
    <%=form_with(model: @entity, url: category_transactions_path, method: :post, local: true) do |f| %>
      <div class="field">
        <%= f.text_field :name, placeholder: "Transaction name" %>
      </div>

      <div class="field">
        <%= f.number_field :amount, placeholder: "Specify amount"%>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %> 
      <%= f.hidden_field :group_id, value: params[:category_id] %> 

      <div class="form-actions">
        <%= f.submit "Save transaction", class: "creator-btns" %>
        <%= link_to "Cancel", categories_path, class: 'delete-btns'%>
      </div>
    <% end %>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="main-categories-page">
  <div class="header category-header">
    <%= link_to raw(image_tag "backwards-arrow.svg"), category_path({id: @transaction.group_id}) %>
    <h1 class="main-headings">Details</h1>
    <%= link_to raw(image_tag "settings-icon.svg"), edit_category_transaction_path({id: @transaction.id, category_id: @transaction.group_id}) %>
  </div>

  <div class="main-content trans-main-content">
    <div class="trans-dashboard">
      <div class="trans-dashboard-header">
        <%case @transaction.group.icon %>
          <%when "entertainment"%>
            <div class="icon-container entertainment">
              <%=image_tag "entertainment.svg" %>
            </div>
          <%when "grosseries"%>
            <div class="icon-container grosseries">
              <%=image_tag "grosseries.svg" %>
            </div>
          <%when "utilities"%>
            <div class="icon-container utilities">
              <%=image_tag "utilities.svg" %>
            </div>
          <%when "housing"%>
            <div class="icon-container housing">
              <%=image_tag "housing.svg" %>
            </div>
          <%when "clothing"%>
            <div class="icon-container clothing">
              <%=image_tag "clothing.svg" %>
            </div>
          <%when "healthcare"%>
            <div class="icon-container healthcare">
              <%=image_tag "healthcare.svg" %>
            </div>
          <%when "transportation"%>
            <div class="icon-container transportation">
              <%=image_tag "transportation.svg" %>
            </div>
          <%when "miscellaneous"%>
            <div class="icon-container miscellaneous">
              <%=image_tag "miscellaneous.svg" %>
            </div>
        <% end %>
        <div class="trans-headings">
          <h2 class="trans-subheadings"><%= @transaction.name %><h2>
        </div>
      </div>
      <div class="trans-dashboard-content">
        <h2 class="trans-subheadings"> Transaction # 10000<%= @transaction.id %></h2>
        <div>
          <small class="trans-dash-date">
            <%= image_tag 'calendar-icon.svg' %>
            <p><%= @transaction.created_at.strftime("%d %B, %Y at %I:%M%p") %><p>
          </small>
        </div>
      </div>
      <div class="trans-footer">
        <h2 class="trans-subheadings sub-uppercase">Total spending</h2>
        <h2 class="trans-subheadings">$ <%= @transaction.amount %>.00</h2>
      </div>
    </div>
  </div>
</div>